# Generated by Django 5.2.8 on 2025-11-10 06:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teacher", "0002_event"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="certificate",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
        migrations.CreateModel(
            name="EventName",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("event_name", models.CharField(max_length=100)),
                (
                    "faculty_name",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="teacher.teacher",
                    ),
                ),
            ],
        ),
    ]
