# Generated by Django 5.2.8 on 2025-11-10 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teacher", "0003_event_certificate_eventname"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="event_name",
            field=models.CharField(max_length=300, null=True),
        ),
    ]
