# Generated by Django 5.2.8 on 2025-11-10 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("teacher", "0004_event_event_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="event",
            name="event_teacher",
        ),
    ]
